runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11"

handlers:
  - url: /static
    static_dir: static  # Directory where static files like CSS, JS, images are stored

  - url: /.*
    script: auto
